### ISSUE TITLE
Dependency React Swipeable Views Appears to have Changed Directory Structure

### ISSUE THREAD

**Issue by asciant** [TeamWertarbyte/material-auto-rotating-carousel#71]
A reproduction can be found here in the example that was never merged into the README.

https://codesandbox.io/s/mystifying-varahamihira-dphsr?fontsize=14

It appears that `react-swipeable-views` may have changed the directory structure in version 13.4, that causes `material-auto-rotating-carousel` to not compile.

I believe the issue sits within the `SwipableCarouselView.js` file between lines 2-4. 
https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/master/src/SwipableCarouselView.js#L2-L4

Downgrading to version 13.3 seemed to fix the issue.

The full error is:
```
[ error ] ./node_modules/material-auto-rotating-carousel/lib/SwipableCarouselView.js
Module not found: Can't resolve 'react-swipeable-views-utils/lib/autoPlay' in '/Users/asciant/Projects/crimson/node_modules/material-auto-rotating-carousel/lib'
{ Error: Cannot find module 'react-swipeable-views-utils/lib/autoPlay'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/asciant/Projects/crimson/node_modules/material-auto-rotating-carousel/lib/SwipableCarouselView.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/asciant/Projects/crimson/node_modules/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js:67:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/asciant/Projects/crimson/node_modules/material-auto-rotating-carousel/lib/index.js:7:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.material-auto-rotating-carousel (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:10997:18)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at Module../components/Detail/Carousel.jsx (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:2785:89)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at Module../components/Detail/Images.jsx (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:3606:67)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at Module../components/Detail/index.jsx (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:4448:65)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at Module../pages/detail.jsx (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:10057:76)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at Object.3 (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:10138:18)
    at __webpack_require__ (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:29:31)
    at /Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:124:18
    at Object.<anonymous> (/Users/asciant/Projects/crimson/.next/server/static/development/pages/detail.js:127:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.requirePage (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/require.js:47:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by leMaik** [comment]
I can't reproduce this with react-swipeable-views 0.13.4 or 0.13.9.
